Task marking and deletion development
DanilByaliy/TaskTracker pull request #3
Opened 2022-06-03 16:38 UTC by DanilByaliy

2022-06-04 10:15 UTC, ILabiak requested changes
need to make a few changes. Everything else is good

2022-06-04 10:15 UTC, ILabiak commented on index.js
> +  if (!tasksArr[index]) throw new Error('There is no such task');
I think there should be tasksArr[index-1], because we show tasks to a person starting with 1. And if he will try to delete first task - second one will be deleted

2022-06-04 10:15 UTC, ILabiak commented on index.test.js
> +    taskTracker.markAsDone(0);
also change test to work with [index-1]

2022-06-05 09:33 UTC, DanilByaliy commented on index.js
> +  if (!tasksArr[index]) throw new Error('There is no such task');
It may be better to decrement the index when passing an argument to a function after reading the arguments from the console

2022-06-05 09:34 UTC, ILabiak approved these changes

2022-06-05 09:38 UTC, merged